language: python
python:
- "2.7"
# command to install dependencies
install:
- pip install pytest pytest-cov
- pip install mockito
- pip install coveralls
- pip install radon
- pip install pep8
# command to run tests
script:
- py.test --cov . --cov-report term-missing
after_success:
- coveralls
- radon cc src/. test/.
- radon mi src/. test/.
- radon raw src/. test/.
- pep8 src/. test/.
notifications:
    email:
        recipients:
            - swak_314@hotmail.com
        on_failure: always